name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    container:
      image: python:3.8

    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: python --version
